### ISSUE TITLE
[Windows] Ripcord crashes unless 'cooldown' is excluded

### ISSUE THREAD

**Issue by ImportTaste** [geniiii/patcher#15]
I only just found out about this project recently, so I don't know if this was an issue in prior versions. Here's my problem:

1. Ripcord.exe patched with the `patcher-windows-x64.exe` command
2. Ripcord.exe copied to two different folders, one for each Discord account
3a. Discord account that is in many different server crashes upon connect (autoconnect is disabled so it's not something else)
3b. Discord account that isn't in any servers does not crash upon connect

After this happened, I figured it must be the cooldown patch since that's the only one relevant to servers specifically. Sure enough:

1. Restored a backup Ripcord.exe and then used the `patcher-windows-x64.exe Ripcord.exe cooldown` command
2. Ripcord.exe copied to both folders again
3. No crash occurs on either account

Then, I reran these tests again, but I joined the account that wasn't in any servers into a server without rate-limited channels. No change.

Finally, I joined the account that wasn't in any servers into a server that did have rate-limited channels. This time, it crashed upon connect just like my other account.

The cooldown patch is the one I really wanted, so for that to be the only one not working is a bummer.

**Comment by geniiii** [comment]
That's odd, it seems to work fine for me, though my executable was manually patched from x64dbg. I might have messed up the offset or something when writing it as a patch, I'll see in a bit.

**Comment by geniiii** [comment]
CI should make a release, give it a minute.

**Comment by ImportTaste** [comment]
> CI should make a release, give it a minute.
> Side note: The cooldown patch won't tell you how much time left until you can send messages. Attempting to send messages when you're not supposed to _could_ trip Discord's anti-spam system, though I've done it myself enough times to where I feel it's not a massive risk. (I should really add this to the README)

Using anything but the official client is always a risk, really. There's just a lot of channels that have a very annoying 2s cooldown or something to prevent spam.

Thanks for the fix.
